language: python
os:
- linux
python:
- 2.7
- 3.6
sudo: false
install:
- pip install -r docs/requirements.txt
script:
- python -m gendocs test
- cd docs
- make html
- cd ..
notifications:
  email:
    recipients:
    - banesullivan@gmail.com
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: banesullivan
  skip_cleanup: true
  password:
    secure: Mtbc6Unudd1vbX2jY4dQh0D4SUiCA+JMmtdCjJNJcz20U7TpGiaOGpXmo8cBoj+iWxTKdPlVCkxOYM7tVPvtJgN1zdX4Eqseete9YufXfS6VC4oYP77TP39Yh87/oNK3PYArG51bSM61IIqrhEawjLs9l98ZdVrGdLN1Mk/fq7Mw1JcSthrGrjY2a//50q7+eKdZfKiJIkkI3hXOoJLzurH/eBFm/2Gbz6fEPRIR70mMb4ch5LvMLhG+zfNY1G4NE2XWR44Cd99AnpbYDR3EGVzAjY9r72b/JJ+B9uvD8VjE5+sqQK+nQF3oHE/NBJ/0U8R6xem4QgmMGlp4RbSv5lYdII/SPj6R2BC+pdjQJnH4p291sh0yGoj7CS1LudSSZFx+HH2zUCVF+0DWJvuVHhtBmvBBNgW2YqfgVooANeFDxoiM/1uRkCtf3rpYr9AGpGTZHmwKpuome1FcheD2ZJ4VySi26UnzD22+xrb182LTR8EQBbnIyvc1N67UOdQtPf/7vcglfQU8hiaY8GX66Cl3t/Ib6vyaU7LlQWDctP2/ha+ViXhPP2qyQTl1NLuXVH1kccpwQRajTdklETyRvXnjle+u27cVJAykTOpmeFHI7c+ULIOqNTNJEyMJtZbS4/KBjnPcskhsrdJobCbU5poOcheBrX9mkRAIxmTHNLA=
  on:
    repo: banesullivan/gendocs
    branch: master
    tags: true
    python: 2.7
